### ISSUE TITLE
Create a design system

### ISSUE THREAD

**Issue by ravgeetdhillon** [cessorg/cess-design-system#1]
Let's take the default bootstrap system and edit it for our personal use.
Here's an example how a design system looks like: https://demos.creative-tim.com/argon-design-system/index.html

This will ensure consistency among the cess websites and will help us to create a brand.

**Comment by hdsingh** [comment]
Good Idea!
@rumeetsingh @Ak-Bhatia What do you think about this?

**Comment by manjots1607** [comment]
Good Idea!!
But for doing this we need to start working on basic things like color palette, fonts, etc & In which format we want to create the design system i.e CSS or JS (like Bootstrap) or UI library for React-based components.
@rumeetsingh  @BharatNischal  @Ak-Bhatia  @ravgeetdhillon  What you think about that??

**Comment by ravgeetdhillon** [comment]
We need to have the colors for the **actions**.
Primary, secondary, warning, success, info and danger. These are actions that will happen on the apps.
Bootstrap has already defined all the components that are used in a website. SO we just need to customize them according to our needs.
There is no need to touch the grid system as it is very well defined.

We can use bootstrap in almost every web project. Another advantage is updates are available in Bootstrap so we can easily update our design system accordingly.

**Comment by BharatNischal** [comment]
Nice idea. I think we should go for it.
